version: '3.9'

services:
  app:
    build: .
    image: atous-sec-network:latest
    container_name: atous-sec-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: atous-sec-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

